removed branch thing

diff --git a/bin/conveyor-project-install b/bin/conveyor-project-install
--- a/bin/conveyor-project-install
+++ b/bin/conveyor-project-install
@@ -9,13 +9,6 @@ if [ ! -f $HOME/.conveyor/config ]; then
 fi
 
 source $HOME/.conveyor/config
-if [ -f $CONVEYOR_PLAYGROUND/dogfoodsoftware.com/third-party/shflags/shflags ]; then
-    source $CONVEYOR_PLAYGROUND/dogfoodsoftware.com/third-party/shflags/shflags
-
-    DEFINE_string 'branch' 'production' 'the branch to checkout after cloning' 'b'
-    FLAGS "$@" || exit $?
-    eval set -- "${FLAGS_ARGV}"
-fi
 
 if [ $# -ne 1 ]; then
     echo "You must provide git repo URL for the project to be installed." >&2
@@ -33,10 +26,9 @@ REPO_BASE=`perl -e '$url = $ARGV[0]; $url =~ s/.+\/([\w-]+).git$/$1/; print $url
 rm -rf $CONVEYOR_PLAYGROUND/.workdir/$REPO_BASE
 cd $CONVEYOR_PLAYGROUND/.workdir
 
-if [ x"$FLAGS_branch" != x"" ]; then
-    git clone --branch $FLAGS_branch $URL
-else
-    git clone $URL
+if ! git clone $URL; then
+    echo "Error while cloning repo at $URL." >&2
+    exit 2
 fi
 
 if [ ! -d $REPO_BASE ]; then
