working up to actual process step

diff --git a/install b/install
--- a/install
+++ b/install
@@ -1,5 +1,25 @@
 #!/bin/bash
 
+# Check if 'nix' is installed / available.
+if [[ ! $(type -P nix-env) ]]; then
+    read -r -p "Nix installation not found, install? (y/N) " ANSWER
+    if [[ "$ANSWER" =~ ^([yY]|[yY][eE][sS])$ ]]; then
+	echo "Implement nix install." >&2
+	exit 500
+    else
+	echo "Cannot proceed without nix installation. Aborting." >&2
+	exit 400 # Better code?
+    fi
+fi
+
+# It seems we have an operationable environment. Setup the 'core' package.
+if [ -d /home/user/playground/dogfoodsoftware.com/conveyor/core ]; then
+    rm -f /home/user/.conveyor/runtime/dogfoodsoftware.com/conveyor-core
+    ln -s /home/user/playground/dogfoodsoftware.com/conveyor/core /home/user/.conveyor/runtime/dogfoodsoftware.com/conveyor-core
+fi
+
+exit 0;
+
 FORCE=false
 CONVEYOR_REPO=https://github.com/DogFoodSoftware/conveyor-core.git
 
@@ -7,10 +27,6 @@ CONVEYOR_REPO=https://github.com/DogFoodSoftware/conveyor-core.git
 # we're the install script, they're set by us.
 export CONVEYOR_PLAYGROUND=$HOME/playground
 
-# We would normally use 'shflags' here as a third-party Conveyor standard
-# component, but this is a standalone script so we use getopt directly. (TODO:
-# ref http://liquid-labs.com/manuals/code-ops/ref/Toolbox#shflags; currently
-# in draft and lacking 'manuals' support in conveyor.)
 TMP=`getopt --name=$0 -a --longoptions=branch:,force,playground: -o b:,p: -- $@`
 eval set -- $TMP
 
